services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.3-ubuntu2204
    container_name: dewaan-mongodb
    ports:
      - 27017:27017
    volumes:
      - type: volume
        target: /data/db
        source: dewaan-mongodb-data
    networks:
      - dewaan-network
    command: --quiet
  web:
    image: dewaan:latest
    container_name: dewaan-web
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3060:3060
    networks:
      - dewaan-network
    environment:
      DEWAAN_MONGO_URI: ${DEWAAN_MONGO_URI}
    volumes:
      - ./released:/dewaan
volumes:
  dewaan-mongodb-data:
networks:
  dewaan-network:
    driver: bridge
