services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.3-ubuntu2204
    container_name: dewaan-mongodb
    ports:
      - ${DEWAAN_MONGO_PORT:-27017}:27017
    volumes:
      - type: volume
        target: /data/db
        source: dewaan-mongodb-data
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - dewaan-network
    command: [--quiet]
    environment: # to change these you have to delete the mongodb data volume
      MONGODB_INITDB_ROOT_USERNAME: ${DEWAAN_MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${DEWAAN_MONGO_PASS}
  dewaan-web:
    image: dewaan:latest
    container_name: dewaan-web
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DEWAAN_WEB_PORT:-3060}:${DEWAAN_WEB_PORT:-3060}
    networks:
      - dewaan-network
    env_file:
      - .env
    volumes:
      - ./released:/dewaan
volumes:
  dewaan-mongodb-data:
networks:
  dewaan-network:
    external: true
